name: eroyal
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.0-134.1.beta <4.0.0"

dependencies:
  another_stepper: ^1.2.2
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_map: ^6.1.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  get: 4.6.6
  google_fonts: ^6.1.0
  intl: ^0.19.0
  rename_app: ^1.3.2
  shared_preferences: ^2.2.1
  url_launcher: ^6.2.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/img_logo.png"
  min_sdk_android: 21

dev_dependencies:
  flutter_lints: 3.0.1
  flutter_test:
    sdk: flutter
  lints: 3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
